# Generated by Django 3.2.9 on 2021-12-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='category',
        ),
    ]
