# Generated by Django 4.0 on 2021-12-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('manga', '0002_remove_manga_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='manga', to='account.user'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='manga.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='account.user')),
            ],
        ),
    ]
