# Generated by Django 4.0 on 2021-12-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
